[package]
name = "veto"
version = "0.1.0"
description = "Minimal, robust JSON-RPC gatekeeper for Anvil and other Ethereum nodes."
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Errors
anyhow = { workspace = true }

# CLI
clap = { version = "4.5.49", default-features = false, features = ["derive", "env", "help", "std", "suggestions", "usage"] }

# HTTP
http = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["env-filter", "fmt", "std"] }

# Workspace crates
veto-config = { workspace = true }
veto-core = { workspace = true }
